### ISSUE TITLE
mou.wav 那是什么

### ISSUE THREAD

**Issue by yigekuyou** [Travellerrr/mirai-otto-hzys#1]
Mirai console 2.16.0 
linux
Overflow

2024-08-09 14:59:12 W/otto-hzys: Exception in executing command `[mirai:source:ids=[], internalIds=[1115709954], from group  to  at ]/hzys 如果某天阿夸毕业了,我不介意亲手结束人类文明`
 command owned by otto-hzys v1.0.2 with NormalMember()
java.lang.RuntimeException: java.io.IOException: Failed to load audio file: mou in /tmp/NCQQ/mcl/data/cn.travellerr.otto-hzys/ysddSources/mou.wav
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.Hzys.gen(Hzys.java:125)
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.Hzys.info(Hzys.java:40)
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.command.GenerateHzys.useVoice(CommandUtil.kt:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:97)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:113)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at kotlin.reflect.jvm.internal.KCallableImpl.callDefaultMethod$kotlin_reflection(KCallableImpl.kt:159)
	at kotlin.reflect.jvm.internal.KCallableImpl.callBy(KCallableImpl.kt:112)
	at net.mamoe.mirai.console.internal.command.CommandReflector$findSubCommands$6$1$invokeSuspend$$inlined$runBIO$1.invoke(CoroutineUtils.kt:23)
	at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
	at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
	at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: java.io.IOException: Failed to load audio file: mou in /tmp/NCQQ/mcl/data/cn.travellerr.otto-hzys/ysddSources/mou.wav
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.Hzys.loadAudioInputStream(Hzys.java:201)
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.Hzys.gen(Hzys.java:62)
	... 21 more
Caused by: java.io.FileNotFoundException: /tmp/NCQQ/mcl/data/cn.travellerr.otto-hzys/ysddSources/mou.wav (没有那个文件或目录)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:213)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:152)
	at java.desktop/com.sun.media.sound.SunFileReader.getAudioInputStream(SunFileReader.java:117)
	at java.desktop/javax.sound.sampled.AudioSystem.getAudioInputStream(AudioSystem.java:1060)
	at otto-hzys-1.0.2.mirai2.jar//cn.travellerr.Hzys.loadAudioInputStream(Hzys.java:197)
	... 22 more

**Comment by Echomirix** [comment]
输入的文本中的 `某` 转化成拼音 `mou` 后在 **音频资源文件夹**  和 **原声大碟文件夹** 中均找不到。
解决方法：
- 在网上手动去找 `mou` 这个音的人声切片
- 找一个与之相近的音复制一份将音频重命名为 `mou.wav`

二选一就行

**Comment by Echomirix** [comment]
https://github.com/Travellerrr/mirai-otto-hzys/commit/1a0dc043e834585114e297210c40d79f949d7286 已上传语音
